name: Continuous Integration

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Build Docker Image
      run: docker build -t backend .

    - name: Run Tests in Docker
      run: docker run --rm backend pytest

    - name: Run Code Coverage in Docker
      run: docker run --rm backend pytest --cov=.

    - name: Run Linter in Docker
      run: docker run --rm backend pylint . --rcfile=pyproject.toml